import typer
from mgcp.dna.codec import encode as codec_encode, decode as codec_decode
from multiprocessing import cpu_count

app = typer.Typer(help="File-level MGC+ DNA codec encode/decode (binary file <-> DNA oligos).")


@app.command("encode")
def encode_cli(
    file_name: str = typer.Argument(..., help="Name of the input file to encode (e.g., data.bin)"),
    max_length: int = typer.Argument(..., help="Maximum oligo length."),
    inner_redundancy: int = typer.Argument(..., help="Number of guess parities per encoded sequence."),
    outer_redundancy: int = typer.Argument(..., help="Number of added redundant encoded sequences."),
    input_path: str = typer.Option(None, help="Path to the input file directory (default: current working directory)."),
    use_marker: bool = typer.Option(True, "--no-marker", help="Use marker-based encoding (disable with --no-marker)."),
    filtered: bool = typer.Option(False, help="Filter the outer encoding subset."),
    seed: int = typer.Option(123456, help="Random seed for reproducibility."),
):
    """
    Encode a binary file into DNA sequences using DNA-MGC+ codec. The max_length parameter sets the target oligo length, which will be matched as closely as possible. The inner_redundancy parameters controls the number of guess parities generated by the inner MGC+ code. The outer_redundancy parameter controls the number of additional sequences generated by the outer RS code. The use_marker option enables the inclusion of periodic markers. If the filtered option is enabled, the encoder will generate 2^16 candidate sequences from which any subset of the desired size can be chosen to represent the file through separate filtering. The indices are randomized using the provided seed for reproducibility. The output is a text file containing the encoded DNA sequences. 
    """
    try:
        codec_encode(
            file_name=file_name,
            max_length=max_length,
            inner_redundancy=inner_redundancy,
            outer_redundancy=outer_redundancy,
            input_path=input_path,
            useMarker=use_marker,
            filtered=filtered,
            seed=seed,
        )
    except Exception as e:
        typer.echo(f"Encoding failed: {e}")


@app.command("decode")
def decode_cli(
    file_name: str = typer.Argument(..., help="Name of the text file to deocde (e.g., run5.txt)."),
    input_path: str = typer.Option(None, help="Path to the input directory (default: current working directory)."),
    processes: int = typer.Option(cpu_count() // 2, help="Number of processes for decoding."),
    seed: int = typer.Option(123456, help="Random seed for reproducibility."),
):
    """
    Decode DNA oligos back into the original binary file using MGC+ codec.
    """
    try:
        codec_decode(
            file_name=file_name,
            input_path=input_path,
            processes=processes,
            seed=seed,
        )
    except Exception as e:
        typer.echo(f"Decoding failed: {e}")


if __name__ == "__main__":
    app()
