import typer
from mgcp.dna.codec import encode as codec_encode, decode as codec_decode
from typing import Optional

app = typer.Typer(help="File-level MGC+ DNA codec encode/decode (binary file <-> DNA oligos).")


@app.command("encode")
def encode_cli(
    file_name: str = typer.Argument(..., help="Name of the input file to encode (e.g., data.bin)"),
    max_length: int = typer.Argument(..., help="Maximum oligo length."),
    inner_redundancy: int = typer.Argument(..., help="Number of guess parities per encoded sequence."),
    outer_rate: float = typer.Argument(..., help="Outer code rate (e.g., 0.9 for about 10% redundancy). Must be in (0, 1)."),
    input_path: str = typer.Option(None, help="Path to the input file directory (default: current working directory)."),
    use_marker: bool = typer.Option(True, "--no-marker", help="Use marker-based encoding (disable with --no-marker)."),
    filtered: bool = typer.Option(False, help="Emit 2^16 candidate DNA sequences per packet and show how many to retain for the requested outer rate."),
    seed: int = typer.Option(123456, help="Random seed for reproducibility."),
    max_seqs_per_packet: Optional[int] = typer.Option(None, help="Unfiltered-mode packet-planning limit (default: 4096); filtered candidate pools are always 2^16."),
):
    """
    Encode a binary file into DNA sequences using DNA-MGC+ codec. The max_length parameter sets the target oligo length, which will be matched as closely as possible. The inner_redundancy parameter controls the number of guess parities generated by the inner MGC+ code. The outer_rate parameter controls the outer code rate (e.g., 0.9 for about 10% redundancy). The use_marker option enables the inclusion of periodic markers. If filtered mode is enabled, every packet contains a full 2^16 candidate pool and the display reports how many sequences to retain from each packet to meet the requested outer rate. Packet header lines make packet boundaries visible in the output text file. The decoder and error generator ignore those headers. The max_seqs_per_packet parameter still controls normal packet planning (default: 4096).
    """
    try:
        codec_encode(
            file_name=file_name,
            max_length=max_length,
            inner_redundancy=inner_redundancy,
            outer_rate=outer_rate,
            input_path=input_path,
            useMarker=use_marker,
            filtered=filtered,
            seed=seed,
            max_seqs_per_packet=max_seqs_per_packet,
        )
    except Exception as e:
        typer.echo(f"Encoding failed: {e}")


@app.command("decode")
def decode_cli(
    file_name: str = typer.Argument(..., help="Name of the text file to decode (e.g., encoded_file.txt)."),
    input_path: str = typer.Option(None, help="Path to the input directory (default: current working directory)."),
    processes: Optional[int] = typer.Option(None, help="Total process budget for decoding (default: automatic)."),
):
    """
    Decode DNA reads back into the original file.

    The random seed is automatically read from encoding_params.json.
    """
    try:
        codec_decode(
            file_name=file_name,
            input_path=input_path,
            processes=processes,
        )
    except Exception as e:
        typer.echo(f"Decoding failed: {e}")


if __name__ == "__main__":
    app()
